apiVersion: v1
kind: Pod
metadata:
  name: kubix
  labels:
    app: kubix
spec:
  containers:
    - name: kubix
      image: ghcr.io/76mrmario/kubix:latest
      imagePullPolicy: Always      
      ports:
        - containerPort: 8080
  restartPolicy: Always
