name: Docker Image CI

on:
  push:
  workflow_dispatch:

jobs:
  write-sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write commit SHA to file
        run: echo "${{ github.sha }}" > commit.sha

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg GIT_SHA=${{ github.sha }} --tag my-image-name:${{ github.sha }}        
        
        
